name: Integration

on:
  # on push for any branch but main
  push:
    #branches-ignore: main
    
  # on workflow call (used by CI workflow on main)
  workflow_call:
    
jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        java: [ 8, 11 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Build & Test
      run: mvn -B clean install
      env:
        GXSERVER_USER: ${{ secrets.GENEXUS_GENERIC_USER }}
        GXSERVER_PASSWORD: ${{ secrets.GENEXUS_GENERIC_PASSWORD }}    


