# This workflow publish to Maven Central in case of a succesfull run of the
# Integration workflow

name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Integration ]
    types: [ completed ]
    branches: [ main ]

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_BUILDER_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Deploy with Maven
      run: mvn -B clean deploy -Pci-cd
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_JLR_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_JLR_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_BUILDER_PASSPHRASE }}
        GXSERVER_USER: ${{ secrets.GENEXUS_GENERIC_USER }}
        GXSERVER_PASSWORD: ${{ secrets.GENEXUS_GENERIC_PASSWORD }}

