# This workflow releases a new version to Maven Central and creates 
# release on GitHub

name: Release

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_BUILDER_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Deploy with Maven
      run: mvn -B release:clean release:prepare release:perform -Pci-cd
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_BUILDER_PASSPHRASE }}
        GXSERVER_USER: ${{ secrets.GENEXUS_GENERIC_USER }}
        GXSERVER_PASSWORD: ${{ secrets.GENEXUS_GENERIC_PASSWORD }}
        GXSERVER_TOKEN: ${{ secrets.GENEXUS_GENERICUSER_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{ github.workspace }}/target/*.jar"
